// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPn7B-ZbtorQ5O2g_vaNCFo4his7M-J4Q',
    appId: '1:154237708960:web:5d13b7759148792c1bb7c5',
    messagingSenderId: '154237708960',
    projectId: 'online-exam-7581c',
    authDomain: 'online-exam-7581c.firebaseapp.com',
    databaseURL: 'https://online-exam-7581c-default-rtdb.firebaseio.com',
    storageBucket: 'online-exam-7581c.firebasestorage.app',
    measurementId: 'G-DKNMKS8QSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGc9AEzC4MSgvrQn7pIRQ4M_l9huSHgvY',
    appId: '1:154237708960:android:b6b2e629020bc2671bb7c5',
    messagingSenderId: '154237708960',
    projectId: 'online-exam-7581c',
    databaseURL: 'https://online-exam-7581c-default-rtdb.firebaseio.com',
    storageBucket: 'online-exam-7581c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrVFhnk1KCKfD_oiL95ZUtfgN4vv0hUQ',
    appId: '1:154237708960:ios:febaa18195dd16ce1bb7c5',
    messagingSenderId: '154237708960',
    projectId: 'online-exam-7581c',
    databaseURL: 'https://online-exam-7581c-default-rtdb.firebaseio.com',
    storageBucket: 'online-exam-7581c.firebasestorage.app',
    iosBundleId: 'com.ananseba.keyboardweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrVFhnk1KCKfD_oiL95ZUtfgN4vv0hUQ',
    appId: '1:154237708960:ios:febaa18195dd16ce1bb7c5',
    messagingSenderId: '154237708960',
    projectId: 'online-exam-7581c',
    databaseURL: 'https://online-exam-7581c-default-rtdb.firebaseio.com',
    storageBucket: 'online-exam-7581c.firebasestorage.app',
    iosBundleId: 'com.ananseba.keyboardweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPn7B-ZbtorQ5O2g_vaNCFo4his7M-J4Q',
    appId: '1:154237708960:web:dc0cf0fdc24ac4461bb7c5',
    messagingSenderId: '154237708960',
    projectId: 'online-exam-7581c',
    authDomain: 'online-exam-7581c.firebaseapp.com',
    databaseURL: 'https://online-exam-7581c-default-rtdb.firebaseio.com',
    storageBucket: 'online-exam-7581c.firebasestorage.app',
    measurementId: 'G-TJ4S4QX185',
  );
}
